name: Python Package using Conda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Initialize Conda
        run: |
          $CONDA/bin/conda init bash
          source ~/.bashrc

      - name: Cache conda packages
        uses: actions/cache@v3
        with:
          path: |
            ~/conda_pkgs_dir
            ~/conda_envs_dir
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}

      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base

      - name: Activate conda environment
        run: conda activate base

      - name: Lint with flake8
        run: flake8 .

      - name: Test with pytest
        run: pytest