name: Python Package using Conda

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # 关键修复点1：强制深度检出代码
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 完整检出提交历史
          path: src       # 指定检出目录

      # 关键修复点2：验证文件存在性
      - name: Validate environment.yml
        working-directory: ./src
        run: |
          if [ ! -f "environment.yml" ]; then
            echo "❌ environment.yml 文件缺失，请检查以下可能："
            echo "1. 文件是否已提交到仓库根目录"
            echo "2. 文件名是否拼写正确"
            exit 1
          fi
          echo "✅ 环境文件验证通过"

      # 关键修复点3：显式初始化 Conda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: base
          environment-file: src/environment.yml  # 显式指定路径

      # 关键修复点4：优化依赖安装
      - name: Install dependencies
        shell: bash -l {0}  # 加载 Conda 环境
        run: |
          conda clean --all -y
          conda env update --file src/environment.yml --name base
          conda list --explicit > spec-file.txt  # 生成依赖清单

      - name: Lint with flake8
        shell: bash -l {0}
        run: flake8 src

      - name: Test with pytest
        shell: bash -l {0}
        run: pytest src